### ISSUE TITLE
Keep current line centered on wave form

### ISSUE THREAD

**Issue by brauliobo** [maxrd2/subtitlecomposer#124]
It would be nice if the current line always stayed on the center of the wave form and the wave form would always scroll down.

This would avoid many times the current line going to the bottom and not seeing enough of the wave form.

Thanks for this great software!

**Comment by maxrd2** [comment]
There is Auto Scroll Padding control in waveform settings now. If you increase it to the maximum the current line will stay centered on the waveform.

**Comment by duck7000** [comment]
Well i tried it but it is way to fast or jumpy to me.

What exactly does this setting do?

**Comment by maxrd2** [comment]
The default setting is how it was before. Scroll padding was fixed 8% before now it's configurable 0-50%, that's the only change that was done.

**Comment by duck7000** [comment]
Thanks for the explanation.

I re-installed the latest version and removed all the subtitlecomposer settings files (there where several)
It seems to be working now like before.
Although i still don't exactly understand what scroll padding is or does?

**Comment by maxrd2** [comment]
Like tooltip settings says:
Autoscroll page when play position reaches ScrollPadding distance (percentage) from page border.
Not sure how better to put it.

**Comment by duck7000** [comment]
Thanks for the explanation, i understand now.

But i still got the feeling that the default setting has changed?
In your previous comment you edited it from 8% to 12.5%?
I lowered the default value to the third marker from left and it feels like that this is the default from previous versions? I could be wrong of course
![Screenshot from 2019-06-17 22-05-50](https://user-images.githubusercontent.com/15360048/59633251-5f10f680-914c-11e9-9ebd-47f2d4e9c50f.png)

**Comment by maxrd2** [comment]
The default from previous versions is 100/8 which is 12.5%. The old default is what felt best for me. The new default is 12% and it can be customized by moving that slider.
